### ISSUE TITLE
Android, iOS and web client

### ISSUE THREAD

**Issue by favadi** [hvnsweeting/pho#1]
Today every task management needs to provide support for those platforms.
:cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: 
and I want to drink a :beer: :beers:

**Comment by bclermont** [comment]
![and windows phone](https://cloud.githubusercontent.com/assets/474302/10244558/b1e252be-6932-11e5-849a-6156e259ce13.png)

and windows phone

**Comment by bclermont** [comment]
![1442322684322](https://cloud.githubusercontent.com/assets/474302/10244662/6bd7adf4-6933-11e5-91b2-ac83859eb0e9.gif)
:+1:

**Comment by bclermont** [comment]
![1442670308537](https://cloud.githubusercontent.com/assets/474302/10244697/a4dfc80c-6933-11e5-912e-af0d25cacc17.jpg)

![1442671543983](https://cloud.githubusercontent.com/assets/474302/10244698/ab01af2a-6933-11e5-9d70-a7d1ea57f308.jpg)

![1442892887874](https://cloud.githubusercontent.com/assets/474302/10244703/b8d292a4-6933-11e5-9caf-6e1cae6a76aa.gif)

![spider_in_mouth](https://cloud.githubusercontent.com/assets/474302/10244711/ccf59268-6933-11e5-9df2-147c655ab45b.gif)

![tennis-ball-sausage](https://cloud.githubusercontent.com/assets/474302/10244714/d3702e0a-6933-11e5-9fa4-633c055b57ba.jpg)

![1440662510336](https://cloud.githubusercontent.com/assets/474302/10244725/f9d51182-6933-11e5-9bed-d42201a9e9a7.gif)

![1440828490376](https://cloud.githubusercontent.com/assets/474302/10244741/16a0c252-6934-11e5-8cbc-8f86d42bbd09.gif)

![1440830296937](https://cloud.githubusercontent.com/assets/474302/10244744/1dc73f48-6934-11e5-8bef-fb1329f3c8f8.gif)

![1440832704851](https://cloud.githubusercontent.com/assets/474302/10244745/226fbec6-6934-11e5-8bfc-6ad50b89012c.gif)
