### ISSUE TITLE
Golang version

### ISSUE THREAD

**Issue by bclermont** [hvnsweeting/pho#2]
I can't install python on my ARM box with 30 Mb free disk. please rewrite it in Go for me to compile a single static binary and install it on my precious ARM

![1441424804861](https://cloud.githubusercontent.com/assets/474302/10244607/0e4551d2-6933-11e5-86eb-0d06068765d7.jpg)

**Comment by favadi** [comment]
I do the initial work here #3. Fell free to merge.

**Comment by bclermont** [comment]
> I do the initial work here: #3. Fell free to merge.

![1442324237963](https://cloud.githubusercontent.com/assets/474302/10244683/83572234-6933-11e5-9680-c2c43f71b684.gif)

**Comment by favadi** [comment]
But it is really good idea bro. :small_red_triangle:
